# JSON - Lab

## Introduction

In this lab, you'll practice navigating JSON data structures.

## Objectives
You will be able to:
* Use the JSON module to load and parse JSON documents

## JSON

### Open the dataset from json

In [1]:
import json

In [2]:
#Your code here
with open('nyc_2001_campaign_finance.json') as f:
    data = json.load(f)

### What is the root data type of the json file?

In [3]:
### Your code here
type(data)

dict

### Navigate to the 'data' key of your loaded json object. What data type is this?

In [4]:
#Your code here
type(data['data'])

list

### Preview the first entry from the value returned by the 'data' key above.

In [5]:
#Your code here
data['data'][56]

[57,
 '286B7B45-55BB-4E38-B789-FFF15FB65EE5',
 57,
 1315925633,
 '392904',
 1315925633,
 '392904',
 '{\n}',
 '2001',
 '569',
 'DeMarco Jr., Alexander A',
 '5',
 None,
 '51',
 'P',
 '0',
 '0',
 '0',
 '0']

### Preview the Entry under meta -> view -> columns (the keys of three successively nested dictionaries)

In [6]:
# Your code here
data['meta']['view']['columns'][5:9]

[{'id': -1,
  'name': 'updated_at',
  'dataTypeName': 'meta_data',
  'fieldName': ':updated_at',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'updated_meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':updated_meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': -1,
  'name': 'meta',
  'dataTypeName': 'meta_data',
  'fieldName': ':meta',
  'position': 0,
  'renderTypeName': 'meta_data',
  'format': {},
  'flags': ['hidden']},
 {'id': 75768833,
  'name': 'ELECTION',
  'dataTypeName': 'number',
  'fieldName': 'election',
  'position': 2,
  'renderTypeName': 'number',
  'tableColumnId': 1518991,
  'width': 196,
  'cachedContents': {'non_null': 284,
   'average': '2001',
   'largest': '2001',
   'null': 1,
   'top': [{'item': '2001', 'count': 20}],
   'smallest': '2001',
   'sum': '568284'},
  'format': {'precisionStyle': 'standard',
   'noCommas': 'true',
   'align': 'right'}}]

### Create a DataFrame from your json data
The previous two questions previewed one entry from the data object within the json file, as well as the column details associated with that data from the meta entry within the json file. Both should have 19 entries. Create a pandas DataFrame of the data. Be sure to use the information from the meta entry to add appropriate column names to your DataFrame.

In [7]:
#Your code here
import pandas as pd
from nested_lookup import nested_lookup

columns = nested_lookup('name', data['meta']['view']['columns'])
df = pd.DataFrame(data['data'], columns=columns)
df.set_index('sid', inplace=True)
df.head()

,id,position,created_at,created_meta,updated_at,updated_meta,meta,ELECTION,CANDID,CANDNAME,OFFICECD,OFFICEBORO,OFFICEDIST,CANCLASS,PRIMARYPAY,GENERALPAY,RUNOFFPAY,TOTALPAY
sid,,,,,,,,,,,,,,,,,,
1,E3E9CC9F-7443-43F6-94AF-B5A0F802DBA1,1,1315925633,392904,1315925633,392904,"{\n ""invalidCells"" : {\n ""1519001"" : ""TOTA...",None,CANDID,CANDNAME,None,OFFICEBORO,None,CANCLASS,None,None,None,None
2,9D257416-581A-4C42-85CC-B6EAD9DED97F,2,1315925633,392904,1315925633,392904,{\n},2001,B4,"Aboulafia, Sandy",5,None,44,P,45410.00,0,0,45410.00
3,B80D7891-93CF-49E8-86E8-182B618E68F2,3,1315925633,392904,1315925633,392904,{\n},2001,445,"Adams, Jackie R",5,None,7,P,11073.00,0,0,11073.00
4,BB012003-78F5-406D-8A87-7FF8A425EE3F,4,1315925633,392904,1315925633,392904,{\n},2001,HF,"Addabbo, Joseph P",5,None,32,P,75350.00,73970.00,0,149320.00
5,945825F9-2F5D-47C2-A16B-75B93E61E1AD,5,1315925633,392904,1315925633,392904,{\n},2001,IR,"Alamo-Estrada, Agustin",5,None,14,P,25000.00,2400.00,0,27400.00

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 285 entries, 1 to 285
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            285 non-null    object
 1   position      285 non-null    int64
 2   created_at    285 non-null    int64
 3   created_meta  285 non-null    object
 4   updated_at    285 non-null    int64
 5   updated_meta  285 non-null    object
 6   meta          285 non-null    object
 7   ELECTION      284 non-null    object
 8   CANDID        285 non-null    object
 9   CANDNAME      285 non-null    object
 10  OFFICECD      284 non-null    object
 11  OFFICEBORO    21 non-null     object
 12  OFFICEDIST    245 non-null    object
 13  CANCLASS      285 non-null    object
 14  PRIMARYPAY    284 non-null    object
 15  GENERALPAY    284 non-null    object
 16  RUNOFFPAY     284 non-null    object
 17  TOTALPAY      284 non-null    object
dtypes: int64(3), object(15)
memory usage: 42.3+ KB

### What's wrong with the first row of the DataFrame?

The first row contains a dictionary and column labels.

In [9]:
# Your code here
df = df.drop(index=1)
df

,id,position,created_at,created_meta,updated_at,updated_meta,meta,ELECTION,CANDID,CANDNAME,OFFICECD,OFFICEBORO,OFFICEDIST,CANCLASS,PRIMARYPAY,GENERALPAY,RUNOFFPAY,TOTALPAY
sid,,,,,,,,,,,,,,,,,,
2,9D257416-581A-4C42-85CC-B6EAD9DED97F,2,1315925633,392904,1315925633,392904,{\n},2001,B4,"Aboulafia, Sandy",5,None,44,P,45410.00,0,0,45410.00
3,B80D7891-93CF-49E8-86E8-182B618E68F2,3,1315925633,392904,1315925633,392904,{\n},2001,445,"Adams, Jackie R",5,None,7,P,11073.00,0,0,11073.00
4,BB012003-78F5-406D-8A87-7FF8A425EE3F,4,1315925633,392904,1315925633,392904,{\n},2001,HF,"Addabbo, Joseph P",5,None,32,P,75350.00,73970.00,0,149320.00
5,945825F9-2F5D-47C2-A16B-75B93E61E1AD,5,1315925633,392904,1315925633,392904,{\n},2001,IR,"Alamo-Estrada, Agustin",5,None,14,P,25000.00,2400.00,0,27400.00
6,9546F502-39D6-4340-B37E-60682EB22274,6,1315925633,392904,1315925633,392904,{\n},2001,BR,"Allen, William A",5,None,9,P,62990.00,0,0,62990.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,C50E6A4C-BDE9-4F12-97F4-95D467013540,281,1315925633,392904,1315925633,392904,{\n},2001,537,"Wilson, John H",5,None,13,P,0,0,0,0
282,04C6D19F-FF63-47B0-B26D-3B8F98B4C16B,282,1315925633,392904,1315925633,392904,{\n},2001,559,"Wooten, Donald T",5,None,42,P,0,0,0,0
283,A451E0E9-D382-4A97-AAD8-D7D382055F8D,283,1315925633,392904,1315925633,392904,{\n},2001,280,"Yassky, David",5,None,33,P,75350.00,75350.00,0,150700.00
284,E84BCD0C-D6F4-450F-B55B-3199A265C781,284,1315925633,392904,1315925633,392904,{\n},2001,274,"Zapiti, Mike",5,None,22,P,12172.00,0,0,12172.00
285,5BBC9676-2119-4FB5-9DAB-DE3F71B7681A,285,1315925633,392904,1315925633,392904,{\n},2001,442,"Zett, Lori M",5,None,24,P,0,0,0,0

## Summary

Congratulations! You've started exploring some more JSON data structures used for the web and got to practice data munging and exploring!